In [1]:
import sys
sys.path.insert(0, "../scripts/")

In [2]:
from dataset import *

In [3]:
env = 'MINDsmall_train'
train_df = load_behavior_data(f'../data/{env}/behaviors.tsv')
train_df = behavior_to_user_item_pair_w_label(train_df)

../data/MINDsmall_train/behaviors.tsv data shape: (156965, 5)


In [4]:
file_name = f'../data/{env}/news.tsv'
df = pd.read_csv(file_name,sep='\t',header=None)
# cols = [IMPRESSION_ID, USER_ID, TIMESTAMP ,HISTORY, IMPRESSIONS]
# df_behaviors.columns = cols
# print(f'{file_name} data shape: {df_behaviors.shape}')

In [5]:
df.shape

(51282, 8)

In [6]:
df.sample(3)

0       1              2  \
9796   N62644    news         newsus   
33470  N12607   autos      autosnews   
12489  N56921  travel  travelarticle   

                                                       3  \
9796   Clarksburg VA deaths: hospital oversights, lap...   
33470  Lane closures Friday night in Providence as Ro...   
12489  Norfolk posted instructions for taking names o...   

                                                       4  \
9796   A series of oversights at a VA medical center ...   
33470  PROVIDENCE -- Lane closures are likely on Rout...   
12489  In the latest escalation in the battle over th...   

                                                   5  \
9796   https://assets.msn.com/labs/mind/AAIOdLS.html   
33470  https://assets.msn.com/labs/mind/BBWLhrE.html   
12489  https://assets.msn.com/labs/mind/AAIOwCo.html   

                                                       6  \
9796   [{"Label": "Virginia", "Type": "G", "WikidataI...   
33470  [{"Label": "Providence, Rhode Island", "Type":...   
12489  [{"Label": "Norfolk, Virginia", "Type": "G", "...   

                                                       7  
9796   [{"Label": "Veterans Health Administration", "...  
33470  [{"Label": "Rhode Island Department of Transpo...  
12489  [{"Label": "Norfolk, Virginia", "Type": "G", "...

In [ ]:
News ID	N37378
Category	sports
SubCategory	golf
Title	PGA Tour winners
Abstract	A gallery of recent winners on the PGA Tour.
URL	https://www.msn.com/en-us/sports/golf/pga-tour-winners/ss-AAjnQjj?ocid=chopendata
Title Entities	[{"Label": "PGA Tour", "Type": "O", "WikidataId": "Q910409", "Confidence": 1.0, "OccurrenceOffsets": [0], "SurfaceForms": ["PGA Tour"]}]
Abstract Entites	[{"Label": "PGA Tour", "Type": "O", "WikidataId": "Q910409", "Confidence": 1.0, "OccurrenceOffsets": [35], "SurfaceForms": ["PGA Tour"]}]

In [12]:
print(train_df.shape)
train_df.sample(3)

(5843444, 3)


user_id news_id  label
5760    U26309   N6099      0
110906  U57655   N4633      0
35660   U25389  N11830      0

In [14]:
env = 'MINDsmall_dev'
test_df = load_behavior_data(f'../data/{env}/behaviors.tsv')
test_df = behavior_to_user_item_pair_w_label(test_df)

In [17]:
print(test_df.shape)
test_df.sample(3)

(2740998, 3)


user_id news_id  label
63285  U89041  N64954      0
18945  U13653  N55084      0
7815   U15212  N60939      0

Library for prepare data

In [1]:
import pandas as pd

In [2]:
USER_ID, NEWS_ID, IMPRESSION_ID, TIMESTAMP, HISTORY, IMPRESSIONS, LABEL = 'user_id', 'news_id', 'impression_id', 'timestamp', 'history', 'impressions', 'label'

In [8]:
env = 'MINDsmall_train'

In [3]:
env = 'MINDlarge_test'

In [4]:
df_behaviors = pd.read_csv(f'../data/{env}/behaviors.tsv',sep='\t',header=None,nrows=100)
df_behaviors.shape

(100, 5)

In [6]:
df_behaviors.head(5)

0        1                       2  \
0  1   U64099  11/19/2019 11:37:45 AM   
1  2  U231077   11/19/2019 5:28:08 AM   
2  3  U606012   11/19/2019 4:46:23 AM   
3  4  U320649   11/21/2019 6:03:51 AM   
4  5  U357840  11/22/2019 10:36:19 AM   

                                                   3  \
0  N121133 N104200 N43255 N55860 N128965 N38014 N...   
1  N45124 N84730 N45128 N104312 N70022 N99111 N26...   
2  N59893 N84662 N90686 N33265 N127225 N120859 N6...   
3  N110863 N7889 N86335 N85056 N115743 N63372 N19...   
4  N98596 N85005 N15713 N67779 N47961 N55571 N666...   

                                                   4  
0  N101071 N15647 N83400 N124838 N57092 N64623 N6...  
1  N14657 N51253 N49521 N126571 N74286 N101071 N1...  
2  N74286 N9250 N26898 N123737 N98301 N80580 N456...  
3  N119559 N37657 N108085 N91287 N39136 N130190 N...  
4  N60658 N43496 N65220 N9125 N63136 N83728 N3208...

In [9]:
df_behaviors.iloc[4].values

array([5, 'U357840', '11/22/2019 10:36:19 AM',
       'N98596 N85005 N15713 N67779 N47961 N55571 N66687 N50459 N16249 N92144 N69847 N34809 N16463 N20694 N89095 N85056 N454 N43585 N72571 N80686 N120745 N26206 N13073 N116367 N53550 N100233 N105296 N128960 N101718 N91985 N48862 N15899 N43826 N126290 N84642 N46994 N66959 N13510 N20943 N41491 N62236 N79909 N39905 N59220 N88809 N50720 N10079 N96713 N72976 N24446 N29362 N93319 N4077 N43085 N32903',
       'N60658 N43496 N65220 N9125 N63136 N83728 N3208 N101425 N5097 N123346 N45098 N57749 N38507 N81701 N118692 N25568 N72227 N49758 N92450 N54934 N57294 N87027 N6001 N91314 N45995 N67769 N39032 N10249 N110323 N90155 N123042 N102182 N127115 N49044 N64892 N124853 N71059'],
      dtype=object)

In [9]:
df_behaviors = pd.read_csv(f'../data/{env}/behaviors.tsv',sep='\t',header=None)
df_behaviors.shape

(156965, 5)

In [5]:
cols = [IMPRESSION_ID, USER_ID, TIMESTAMP ,HISTORY, IMPRESSIONS]
df_behaviors.columns = cols
df_behaviors.head()

impression_id user_id              timestamp  \
0              1  U13740  11/11/2019 9:05:58 AM   
1              2  U91836  11/12/2019 6:11:30 PM   
2              3  U73700  11/14/2019 7:01:48 AM   
3              4  U34670  11/11/2019 5:28:05 AM   
4              5   U8125  11/12/2019 4:11:21 PM   

                                             history  \
0  N55189 N42782 N34694 N45794 N18445 N63302 N104...   
1  N31739 N6072 N63045 N23979 N35656 N43353 N8129...   
2  N10732 N25792 N7563 N21087 N41087 N5445 N60384...   
3  N45729 N2203 N871 N53880 N41375 N43142 N33013 ...   
4                        N10078 N56514 N14904 N33740   

                                         impressions  
0                                  N55689-1 N35729-0  
1  N20678-0 N39317-0 N58114-0 N20495-0 N42977-0 N...  
2  N50014-0 N23877-0 N35389-0 N49712-0 N16844-0 N...  
3                N35729-0 N33632-0 N49685-1 N27581-0  
4  N39985-0 N36050-0 N16096-0 N8400-1 N22407-0 N6...

Training data can be in multiple formats

- user_id, item_id
- user_id, item_id, impressions
- user_id, history

In [7]:
df_behaviors.user_id.nunique()

50000

#### user_id, item_id, impressions -> Training data

In [16]:
from sklearn import preprocessing

In [17]:
user_2_idx = preprocessing.LabelEncoder()
news_2_idx = preprocessing.LabelEncoder()

In [8]:
tdf = df_behaviors.copy()

In [13]:
# %%timeit///
df_behaviors['impressions2'] = df_behaviors[IMPRESSIONS].str.split(' ')
df_behaviors = df_behaviors.explode('impressions2')

In [14]:
df_behaviors.sample(3)

impression_id user_id               timestamp  \
34221           34222  U84517   11/11/2019 8:42:15 AM   
145191         145192  U78340   11/10/2019 6:52:20 AM   
97200           97201   U2759  11/12/2019 10:15:37 AM   

                                                  history  \
34221   N12824 N11282 N41777 N52677 N60844 N44559 N446...   
145191  N2955 N10818 N30662 N56521 N33835 N20840 N3383...   
97200   N45794 N43955 N11523 N35710 N54522 N14552 N131...   

                                              impressions impressions2  
34221   N32087-0 N56227-0 N25437-0 N20729-0 N5890-0 N1...     N54868-0  
145191  N26179-0 N17252-0 N59390-0 N22329-0 N23784-0 N...     N36837-0  
97200   N20486-0 N34977-0 N41354-0 N22215-0 N1468-0 N3...     N27441-0

In [18]:
df_behaviors['label'] = df_behaviors['impressions2'].apply(lambda x: int(x[-1]))
df_behaviors['news_id'] = df_behaviors['impressions2'].apply(lambda x: x[:-2])

In [21]:
tdf = df_behaviors[[USER_ID, NEWS_ID, LABEL]]
tdf.sample(3)

user_id news_id  label
130396   U9813   N5370      0
69966    U6132  N61363      0
151849  U47139  N47851      0

In [22]:
tdf[NEWS_ID].nunique()

20288

In [26]:
tdf.to_pickle('user_news_label.pkl')

In [ ]:
le.fit([1, 2, 2, 6])
>>> le.classes_
array([1, 2, 6])
>>> le.transform([1, 1, 2, 6])
array([0, 0, 1, 2]...)
>>> le.inverse_transform([0, 0, 1, 2])
array([1, 1, 2, 6])

In [10]:

from sklearn.metrics import roc_auc_score

In [15]:
y = [0,0,1,1,1]
y_hat = [0.3,0.4,0.5,0.6,0.7]

In [16]:
roc_auc_score(y,y_hat)

1.0